from pathlib import Path
root=Path('/tmp/wolfe_batch11')
# Retailer coords
p=root/'backend/src/main/java/com/wolfe/retailer/Retailer.java'
s=p.read_text()
s=s.replace('    @Column(name = "delivery_radius_km", nullable = false)\n    private BigDecimal deliveryRadiusKm = new BigDecimal("25.0");', '    @Column(name = "delivery_radius_km", nullable = false)\n    private BigDecimal deliveryRadiusKm = new BigDecimal("25.0");\n\n    @Column(precision = 9, scale = 6) private BigDecimal latitude;\n    @Column(precision = 9, scale = 6) private BigDecimal longitude;')
s=s.replace('    public BigDecimal getDeliveryRadiusKm() { return deliveryRadiusKm; }\n    public void setDeliveryRadiusKm(BigDecimal deliveryRadiusKm) { this.deliveryRadiusKm = deliveryRadiusKm; touch(); }', '    public BigDecimal getDeliveryRadiusKm() { return deliveryRadiusKm; }\n    public void setDeliveryRadiusKm(BigDecimal deliveryRadiusKm) { this.deliveryRadiusKm = deliveryRadiusKm; touch(); }\n    public BigDecimal getLatitude() { return latitude; }\n    public BigDecimal getLongitude() { return longitude; }\n    public void setCoordinates(BigDecimal latitude, BigDecimal longitude) {\n        if (latitude != null && (latitude.compareTo(new BigDecimal("-90")) < 0 || latitude.compareTo(new BigDecimal("90")) > 0)) throw new IllegalArgumentException("invalid retailer latitude");\n        if (longitude != null && (longitude.compareTo(new BigDecimal("-180")) < 0 || longitude.compareTo(new BigDecimal("180")) > 0)) throw new IllegalArgumentException("invalid retailer longitude");\n        this.latitude = latitude; this.longitude = longitude; touch();\n    }')
p.write_text(s)
# Order coords
p=root/'backend/src/main/java/com/wolfe/order/Order.java'; s=p.read_text()
s=s.replace('    @Column(name = "support_number", nullable = false, unique = true, length = 16) private String supportNumber;', '    @Column(name = "support_number", nullable = false, unique = true, length = 16) private String supportNumber;\n    @Column(precision = 9, scale = 6) private java.math.BigDecimal latitude;\n    @Column(precision = 9, scale = 6) private java.math.BigDecimal longitude;')
s=s.replace('    public String getSupportNumber() { return supportNumber; }', '    public String getSupportNumber() { return supportNumber; }\n    public java.math.BigDecimal getLatitude() { return latitude; }\n    public java.math.BigDecimal getLongitude() { return longitude; }\n    public void setCoordinates(java.math.BigDecimal latitude, java.math.BigDecimal longitude) {\n        if (latitude != null && (latitude.compareTo(new java.math.BigDecimal("-90")) < 0 || latitude.compareTo(new java.math.BigDecimal("90")) > 0)) throw new IllegalArgumentException("invalid order latitude");\n        if (longitude != null && (longitude.compareTo(new java.math.BigDecimal("-180")) < 0 || longitude.compareTo(new java.math.BigDecimal("180")) > 0)) throw new IllegalArgumentException("invalid order longitude");\n        this.latitude = latitude; this.longitude = longitude;\n    }')
p.write_text(s)
# Controller create coords
p=root/'backend/src/main/java/com/wolfe/order/OrderController.java'; s=p.read_text()
s=s.replace('r.customerId(), r.customerName(), r.customerEmail(), r.phone(), r.address(), r.city(), r.pincode(),\n                r.paymentMethod()', 'r.customerId(), r.customerName(), r.customerEmail(), r.phone(), r.address(), r.city(), r.pincode(),\n                r.latitude(), r.longitude(), r.paymentMethod()')
s=s.replace('@NotBlank @Pattern(regexp = "^[1-9]\\d{5}$") String pincode,\n            @NotBlank @Size(max = 40) String paymentMethod,', '@NotBlank @Pattern(regexp = "^[1-9]\\d{5}$") String pincode,\n            @DecimalMin("-90.0") @DecimalMax("90.0") Double latitude,\n            @DecimalMin("-180.0") @DecimalMax("180.0") Double longitude,\n            @NotBlank @Size(max = 40) String paymentMethod,')
p.write_text(s)
# OrderService record and constructor/save
p=root/'backend/src/main/java/com/wolfe/order/OrderService.java'; s=p.read_text()
s=s.replace('r.customerName().trim(), r.customerEmail().trim().toLowerCase(), r.phone().trim(),\n                r.address().trim(), r.city().trim(), r.pincode().trim()\n        ));', 'r.customerName().trim(), r.customerEmail().trim().toLowerCase(), r.phone().trim(),\n                r.address().trim(), r.city().trim(), r.pincode().trim()\n        ));\n        order.setCoordinates(r.latitude() == null ? null : java.math.BigDecimal.valueOf(r.latitude()),\n                r.longitude() == null ? null : java.math.BigDecimal.valueOf(r.longitude()));')
s=s.replace('String pincode, String paymentMethod, String shippingMethod, String couponCode, List<Item> items, String idempotencyKey\n    ) {', 'String pincode, Double latitude, Double longitude, String paymentMethod, String shippingMethod, String couponCode, List<Item> items, String idempotencyKey\n    ) {')
s=s.replace('String pincode, String paymentMethod, String shippingMethod, String couponCode, List<Item> items) {\n            this(customerId, customerName, customerEmail, phone, address, city, pincode, paymentMethod, shippingMethod, couponCode, items, java.util.UUID.randomUUID().toString());', 'String pincode, String paymentMethod, String shippingMethod, String couponCode, List<Item> items) {\n            this(customerId, customerName, customerEmail, phone, address, city, pincode, null, null, paymentMethod, shippingMethod, couponCode, items, java.util.UUID.randomUUID().toString());')
p.write_text(s)
# Retailer admin coords
p=root/'backend/src/main/java/com/wolfe/retailer/AdminRetailerController.java'; s=p.read_text()
s=s.replace('BigDecimal deliveryRadiusKm,\n            @jakarta.validation.constraints.DecimalMin("0.0")', 'BigDecimal deliveryRadiusKm,\n            @jakarta.validation.constraints.DecimalMin("-90.0") @jakarta.validation.constraints.DecimalMax("90.0") BigDecimal latitude,\n            @jakarta.validation.constraints.DecimalMin("-180.0") @jakarta.validation.constraints.DecimalMax("180.0") BigDecimal longitude,\n            @jakarta.validation.constraints.DecimalMin("0.0")',1)
s=s.replace('if (req.deliveryRadiusKm() != null) r.setDeliveryRadiusKm(req.deliveryRadiusKm());\n        if (req.commissionRate()', 'if (req.deliveryRadiusKm() != null) r.setDeliveryRadiusKm(req.deliveryRadiusKm());\n        r.setCoordinates(req.latitude(), req.longitude());\n        if (req.commissionRate()',1)
s=s.replace('BigDecimal deliveryRadiusKm,\n            String status,', 'BigDecimal deliveryRadiusKm,\n            @jakarta.validation.constraints.DecimalMin("-90.0") @jakarta.validation.constraints.DecimalMax("90.0") BigDecimal latitude,\n            @jakarta.validation.constraints.DecimalMin("-180.0") @jakarta.validation.constraints.DecimalMax("180.0") BigDecimal longitude,\n            String status,',1)
s=s.replace('if (req.deliveryRadiusKm() != null) r.setDeliveryRadiusKm(req.deliveryRadiusKm());\n        if (req.status()', 'if (req.deliveryRadiusKm() != null) r.setDeliveryRadiusKm(req.deliveryRadiusKm());\n        if (req.latitude() != null || req.longitude() != null) r.setCoordinates(req.latitude(), req.longitude());\n        if (req.status()',1)
p.write_text(s)
# allocation radius filter
p=root/'backend/src/main/java/com/wolfe/retailer/RetailerAllocationService.java'; s=p.read_text()
old='''            boolean serviceable = areas.stream().anyMatch(a -> a.isActive() && (\n                    a.getPincode().trim().equalsIgnoreCase(order.getPincode().trim()) ||\n                    a.getCity().trim().equalsIgnoreCase(order.getCity().trim())\n            ));'''
new='''            boolean areaServiceable = areas.stream().anyMatch(a -> a.isActive() && (\n                    a.getPincode().trim().equalsIgnoreCase(order.getPincode().trim()) ||\n                    a.getCity().trim().equalsIgnoreCase(order.getCity().trim())\n            ));\n            boolean radiusServiceable = false;\n            if (order.getLatitude() != null && order.getLongitude() != null && r.getLatitude() != null && r.getLongitude() != null && r.getDeliveryRadiusKm() != null) {\n                radiusServiceable = haversineKm(order.getLatitude().doubleValue(), order.getLongitude().doubleValue(),\n                        r.getLatitude().doubleValue(), r.getLongitude().doubleValue()) <= r.getDeliveryRadiusKm().doubleValue();\n            }\n            boolean serviceable = radiusServiceable || areaServiceable;'''
s=s.replace(old,new)
insert='''\n    private static double haversineKm(double lat1, double lon1, double lat2, double lon2) {\n        double dLat = Math.toRadians(lat2 - lat1);\n        double dLon = Math.toRadians(lon2 - lon1);\n        double a = Math.sin(dLat / 2) * Math.sin(dLat / 2)\n                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))\n                * Math.sin(dLon / 2) * Math.sin(dLon / 2);\n        return 6371.0088 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));\n    }\n'''
pos=s.rfind('\n}')
s=s[:pos]+insert+s[pos:]
p.write_text(s)
# migration
mig=root/'backend/src/main/resources/db/migration/V48__inventory_reconciliation_and_delivery_coordinates.sql'
mig.write_text('''ALTER TABLE retailers ADD COLUMN IF NOT EXISTS latitude NUMERIC(9,6);\nALTER TABLE retailers ADD COLUMN IF NOT EXISTS longitude NUMERIC(9,6);\nALTER TABLE orders ADD COLUMN IF NOT EXISTS latitude NUMERIC(9,6);\nALTER TABLE orders ADD COLUMN IF NOT EXISTS longitude NUMERIC(9,6);\nALTER TABLE retailers ADD CONSTRAINT ck_retailer_coordinates_lat CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90);\nALTER TABLE retailers ADD CONSTRAINT ck_retailer_coordinates_lon CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180);\nALTER TABLE orders ADD CONSTRAINT ck_order_coordinates_lat CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90);\nALTER TABLE orders ADD CONSTRAINT ck_order_coordinates_lon CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180);\n''')
