-- Cart variant support: preserve existing rows while allowing one cart line per exact variant.
ALTER TABLE cart_items ADD COLUMN variant_id BIGINT;

ALTER TABLE cart_items DROP CONSTRAINT IF EXISTS cart_items_pkey;
ALTER TABLE cart_items ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cart_items ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);

ALTER TABLE cart_items
    ADD CONSTRAINT fk_cart_items_variant
    FOREIGN KEY (variant_id) REFERENCES product_variants(id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cart_customer_product_variant
    ON cart_items (customer_id, product_id, COALESCE(variant_id, 0));
CREATE INDEX IF NOT EXISTS idx_cart_customer ON cart_items(customer_id);
CREATE INDEX IF NOT EXISTS idx_cart_variant ON cart_items(variant_id);
