CREATE TABLE IF NOT EXISTS staff_alerts (id BIGSERIAL PRIMARY KEY,type VARCHAR(40) NOT NULL,subject VARCHAR(200) NOT NULL,message VARCHAR(2000) NOT NULL,created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,acknowledged BOOLEAN NOT NULL DEFAULT FALSE);
CREATE INDEX IF NOT EXISTS idx_staff_alert_created ON staff_alerts(created_at);
