ALTER TABLE product_media ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE visual_contents ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE accessory_options ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
